<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_fontes',
		'title' => 'Fontes',
		'fields' => array (
			array (
				'key' => 'field_58c1ac6ff6b3b',
				'label' => 'E-mail',
				'name' => 'email',
				'type' => 'text',
				'instructions' => 'Endereço de e-mail da fonte',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_58c1ad2de0f01',
				'label' => 'Telefone',
				'name' => 'telefone',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'fonte',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_noticias',
		'title' => 'Notícias',
		'fields' => array (
			array (
				'key' => 'field_5751ea4f92ebc',
				'label' => 'Imagem para o slider',
				'name' => 'destaque',
				'type' => 'image',
				'instructions' => 'Insira a imagem de destaque com tamanho mínimo de 1200px por 400px ',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_57531525b925d',
				'label' => 'Chamada',
				'name' => 'chamada',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57a14fdfc825d',
				'label' => 'Imagem quadrada',
				'name' => 'img_quadrada',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'quadrada',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'noticia',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_praticas-sustentaveis-descricao',
		'title' => 'Práticas Sustentáveis - Descrição',
		'fields' => array (
			array (
				'key' => 'field_56cc5d2f9931b',
				'label' => 'Vídeo',
				'name' => 'video',
				'type' => 'oembed',
				'preview_size' => 0,
				'returned_size' => 0,
				'returned_format' => 'html',
			),
			array (
				'key' => 'field_56cc5c8f99316',
				'label' => 'Público-alvo',
				'name' => 'publico-alvo',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56cc5cbe99319',
				'label' => 'Local de implementação',
				'name' => 'local_de_implementacao',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56cc5cb299318',
				'label' => 'Resultados',
				'name' => 'resultados',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_56cc5ca099317',
				'label' => 'Descrição das ações',
				'name' => 'descricao_das_acoes',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_56cc5c7e99315',
				'label' => 'Objetivo',
				'name' => 'objetivo',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'pratica',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_praticas-sustentaveis-identificacao',
		'title' => 'Práticas Sustentáveis - Identificação',
		'fields' => array (
			array (
				'key' => 'field_56cc5beb20d87',
				'label' => 'Resumo da prática',
				'name' => 'resumo_da_pratica',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => 800,
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_56da45eda5831',
				'label' => 'UF',
				'name' => 'uf',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56da45f6a5832',
				'label' => 'Cidade',
				'name' => 'cidade',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56e7a1b6ae169',
				'label' => 'E-mail de cadastro',
				'name' => 'e-mail_de_cadastro',
				'type' => 'email',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_56d8bf7f672b1',
				'label' => 'Nome da entidade ou responsável',
				'name' => 'nome_da_entidade',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56cc5b8acf4b3',
				'label' => 'Telefone',
				'name' => 'telefone_da_entidade',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56cc5b3e16c46',
				'label' => 'Endereço',
				'name' => 'endereco_da_entidade',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56cc5b6e70a32',
				'label' => 'Site',
				'name' => 'site_da_entidade',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56cc5b81cf4b2',
				'label' => 'E-mail de contato',
				'name' => 'e-mail_de_contato',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'pratica',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_publicacao',
		'title' => 'Publicação',
		'fields' => array (
			array (
				'key' => 'field_5754962992125',
				'label' => 'Arquivo para download',
				'name' => 'publicacao_arquivo',
				'type' => 'file',
				'save_format' => 'url',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'publicacao',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_slider',
		'title' => 'slider',
		'fields' => array (
			array (
				'key' => 'field_575315882afd4',
				'label' => 'link',
				'name' => 'link',
				'type' => 'text',
				'instructions' => 'Coloque o link completo com http:// ou https://',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'slide',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_videos',
		'title' => 'Vídeos',
		'fields' => array (
			array (
				'key' => 'field_5754c41f677a6',
				'label' => 'endereco do vídeo',
				'name' => 'video',
				'type' => 'oembed',
				'preview_size' => 'destaques-categoria',
				'returned_size' => 'destaques-categoria',
				'returned_format' => 'html',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'video',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
